# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10'

target 'RadioPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RadioPlayer
  pod 'Alamofire', '~> 4.0'
  #GG ADMOB
  pod 'Google-Mobile-Ads-SDK'

end
